# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb07f51734d991dff2bf57f4bb0f29cd5b86ea13f2e8c1dd23207e4dff4f21ad2b57cc937d3e97de8a89ad66fffdc4c0a4359f5e892c2ccae5b245d458a81a68

test:
  secret_key_base: f89323dd8678b611f8181e915678ef1961a17c6e3b7c37e19da526a1e1b7c19a9ecb1e336a5dde93fbaefc238fce0a936772158d4a6d1d8fdfbfa74e4757faa2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
